### ISSUE TITLE
`map_height_fitter` fails to detect map ground

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#3993]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

In a simulated environment, the `map_height_fitter` fails to locate the PCD map ground and the initial position ends up 150 meters under the map (z=0):

![image](https://github.com/autowarefoundation/autoware.universe/assets/18645627/0437bfc8-2758-41af-a85f-eac94e1e3bff)

![image](https://github.com/autowarefoundation/autoware.universe/assets/18645627/6fb3b25a-e509-425a-a6c7-31392ed85aaa)

In the log, I see:
```
[rviz2-69] [INFO 1686888780.878679225] [rviz2]: Setting estimate pose: Frame:map, Position(52451.3, 65997.6, 0), Orientation(0, 0, -0.833062, 0.55318) = Angle: -1.96924 (operator()() at ./src/main.cpp:62)
[initial_pose_adaptor-66] [INFO 1686888780.879371161] [default_ad_api.helpers.initial_pose_adaptor]: map fit1: 52451.301 65997.586 0.000 (fit() at /home/sig/autoware/src/universe/autoware.universe/map/map_height_fitter/src/map_height_fitter.cpp:169)
[initial_pose_adaptor-66] [INFO 1686888780.879819454] [default_ad_api.helpers.initial_pose_adaptor]: Send request to map_loader (get_partial_point_cloud_map() at /home/sig/autoware/src/universe/autoware.universe/map/map_height_fitter/src/map_height_fitter.cpp:103)
[initial_pose_adaptor-66] [INFO 1686888780.881185460] [default_ad_api.helpers.initial_pose_adaptor]: Loaded partial pcd map from map_loader (grid size: 0) (get_partial_point_cloud_map() at /home/sig/autoware/src/universe/autoware.universe/map/map_height_fitter/src/map_height_fitter.cpp:115)
[initial_pose_adaptor-66] Failed to find match for field 'x'.
[initial_pose_adaptor-66] Failed to find match for field 'y'.
[initial_pose_adaptor-66] Failed to find match for field 'z'.
[initial_pose_adaptor-66] [INFO 1686888780.881249434] [default_ad_api.helpers.initial_pose_adaptor]: map fit2: 52451.301 65997.586 0.000 (fit() at /home/sig/autoware/src/universe/autoware.universe/map/map_height_fitter/src/map_height_fitter.cpp:189)
```

I don't know if it is related, but PCL complains it cannot find xyz fields. Lokking at the code, it looks like the error comes from here:

https://github.com/autowarefoundation/autoware.universe/blob/2465bbfa1de791794b2f49088ef301e20ad7e568/map/map_height_fitter/src/map_height_fitter.cpp#L120-L133 

As you can see, the `pcd_msg` message is created from the concatenation of all partials pointclouds, but its `fields` are never set. Maybe it causes `pcl::fromROSMsg()` to fail and return an empty cloud?

### Expected behavior

ground height correctly detected

### Actual behavior

ground height not detected

### Steps to reproduce

N/A

**Comment by VRichardJP** [comment]
I think there is a design issue with the `pointcloud_map_loader`:
- `enable_partial_load` is set to `true` by default in the `autoware_launch`
- if this flag is set, then `map_height_fitter` call the service to replace the current map
- yet, if the flag is set but only 1 pcd map is used, the service returns an empty cloud.

Considering that using only one PCD map should be the default use case, I don't think the current behaviour is correct.

**Comment by kminoda** [comment]
Thank you for the report! We encountered a similar issue before, which I believe was resolved with this PR: https://github.com/autowarefoundation/autoware.universe/pull/3863. Would you check if the PR is incorporated in your Autoware?

**Comment by VRichardJP** [comment]
@kminoda Unfortunatelly, I just pulled latest autoware and lost track of the exact hash I was working on, but I see my previous pull was on June 16, so after your PR has been merged. I also remember finding the cyclinder overlap function as I inspected the issue.

I fixed the issue by disabling the partial map loading (I have only 1 pcd file).

**Comment by VRichardJP** [comment]
The problem still occurs:
![image](https://github.com/autowarefoundation/autoware.universe/assets/18645627/4cb321a9-de77-4a34-a9c8-2473715a28fb)

The initial pose is exactly at z=0 in map frame, while the actual points are ~150 meters above.

**Comment by kminoda** [comment]
Hmm, I see no problem in my Autoware (also latest). I translated a `sample-map-rosbag` from tutorial with `pcl_transform_point_cloud pointcloud_map.pcd output.pcd -trans 0.0,0.0,200.0`, load it in Autoware and run with the tutorial rosbag. It starts successfully with z-axis also aligned.

What kind of map are you using? Is it your own map? It does not include any noise points especially around z=0, right?

![Screenshot from 2023-06-27 15-58-07](https://github.com/autowarefoundation/autoware.universe/assets/44218668/2c6ddb41-2708-477f-b031-3ef94f568172)

**Comment by VRichardJP** [comment]
With the dynamic map loading disabled I have no problem, even if I move the map up as you did:
![image](https://github.com/autowarefoundation/autoware.universe/assets/18645627/a64aa3a5-6876-4d92-9390-50fa57407079)

However if dynamic map loading is enabled (the default autoware_launch), the map does not load at all. Localization is never initialized.
![image](https://github.com/autowarefoundation/autoware.universe/assets/18645627/6215dfbb-ea6f-4eb3-a3c9-07e943507fb6)

In the logs I see this:
```
[ndt_scan_matcher-31] [INFO 1687854665.894965925] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)
[component_container_mt-1] [INFO 1687854665.905057830] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[ekf_localizer-33] [WARN 1687854666.327254766] [localization.pose_twist_fusion_filter.ekf_localizer]: The node is not activated. Provide initial pose to pose_initializer (warnThrottle() at /home/sig/autoware/src/universe/autoware.universe/localization/ekf_localizer/include/ekf_localizer/warning.hpp:34)
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
[rviz2-68] Warning: Invalid frame ID "viewer" passed to canTransform argument source_frame - frame does not exist
[rviz2-68]          at line 93 in ./src/buffer_core.cpp
```

Looks like the pcd loader service is not started properly.

**Comment by kminoda** [comment]
Sorry for repeating it again, but could you double check that your Autoware is updated to the latest version properly with clean build? I will do it for my environment as well as soon as my other task is done.

Also, could you provide the log around
- ndt_scan_matcher
- map_loader
- map_height_fitter
- pose_initializer
- ekf_localizer

by e.g. doing `ros2 launch autoware_launch ... | grep -e ndt_scan_matcher -e map_loader ...` ?


BTW at least from the log you've provided at the top of this issue,
```
[rviz2-69] [INFO 1686888780.878679225] [rviz2]: Setting estimate pose: Frame:map, Position(52451.3, 65997.6, 0), Orientation(0, 0, -0.833062, 0.55318) = Angle: -1.96924 (operator()() at ./src/main.cpp:62)
[initial_pose_adaptor-66] [INFO 1686888780.879371161] [default_ad_api.helpers.initial_pose_adaptor]: map fit1: 52451.301 65997.586 0.000 (fit() at /home/sig/autoware/src/universe/autoware.universe/map/map_height_fitter/src/map_height_fitter.cpp:169)
[initial_pose_adaptor-66] [INFO 1686888780.879819454] [default_ad_api.helpers.initial_pose_adaptor]: Send request to map_loader (get_partial_point_cloud_map() at /home/sig/autoware/src/universe/autoware.universe/map/map_height_fitter/src/map_height_fitter.cpp:103)
[initial_pose_adaptor-66] [INFO 1686888780.881185460] [default_ad_api.helpers.initial_pose_adaptor]: Loaded partial pcd map from map_loader (grid size: 0) (get_partial_point_cloud_map() at /home/sig/autoware/src/universe/autoware.universe/map/map_height_fitter/src/map_height_fitter.cpp:115)
[initial_pose_adaptor-66] Failed to find match for field 'x'.
[initial_pose_adaptor-66] Failed to find match for field 'y'.
[initial_pose_adaptor-66] Failed to find match for field 'z'.
[initial_pose_adaptor-66] [INFO 1686888780.881249434] [default_ad_api.helpers.initial_pose_adaptor]: map fit2: 52451.301 65997.586 0.000 (fit() at /home/sig/autoware/src/universe/autoware.universe/map/map_height_fitter/src/map_height_fitter.cpp:189)
```

the map_loader seems to have started successfully, but just to load the target pointcloud given the query.

**Comment by VRichardJP** [comment]
I just pulled and recompiled a clean autoware code:
```
=== src/core/autoware.core (git) ===
commit 99891401473b5740e640f5a0cc0412c0984b8e0b (HEAD -> main, origin/main, origin/HEAD, humble_with_targets)
Author: awf-autoware-bot[bot] <94889083+awf-autoware-bot[bot]@users.noreply.github.com>

    chore: sync files (#78)

commit 794aed1b9dd5eaf5e1ce349fb96ac7adb87a8f9a
Author: awf-autoware-bot[bot] <94889083+awf-autoware-bot[bot]@users.noreply.github.com>

    chore: sync files (#76)

commit 0a3421239fcf576d3e73036c6b5da1daf2b8c8d0
Author: awf-autoware-bot[bot] <94889083+awf-autoware-bot[bot]@users.noreply.github.com>

    chore: sync files (#75)
=== src/core/autoware_adapi_msgs (git) ===
commit 7cd80335ad1a4edc1955de5062dd5a4bd9d4de7b (HEAD -> main, origin/main, origin/HEAD)
Author: Kah Hooi Tan <41041286+tkhmy@users.noreply.github.com>

    feat(autoware_adapi_v1_msgs): add vehicle status msgs (#24)

commit 6de4fe5858d96b2e787847b29c36858e06ae3c98
Author: awf-autoware-bot[bot] <94889083+awf-autoware-bot[bot]@users.noreply.github.com>

    chore: sync files (#37)

commit 8d0fc25179d62f9de6d3ec235f652b42e3c0dc11
Author: Kosuke Takeuchi <kosuke.tnp@gmail.com>

    refactor(start_planner): rename pull out to start planner (#36)
=== src/core/autoware_common (git) ===
commit 536b628d6cc87ddf877efb351ff9d38f12fec620 (HEAD -> main, origin/main, origin/HEAD)
Author: Kosuke Takeuchi <kosuke.tnp@gmail.com>

    feat(lanelet2_extension): move combineLanelets unnamed namespace (#193)

commit d65a73812d63f0ddf6134e07b58d351c626dfa19
Author: Ahmed Ebrahim <36835765+ahmeddesokyebrahim@users.noreply.github.com>

    refactor(no_drivable_lane): updating no_drivable_lane doc link after refactoring updates (#188)

commit 268a8c84c6de0e864fd159f15fae03beb04f0e93
Author: Kenji Miyake <31987104+kenji-miyake@users.noreply.github.com>

    ci(pre-commit): add check-jsonschema (#189)
=== src/core/autoware_msgs (git) ===
commit 52a856d29601860413e4261079e0bf9205c737d1 (HEAD -> main, origin/main, origin/HEAD)
Author: Mingyu1991 <115005477+Mingyu1991@users.noreply.github.com>

    revert: "fix(autoware_perception_msgs): add Header to tlr messages and change TrafficLightElement.msg status" (#69)

commit 18588df6eb7e7f694bd725bebd44f569f616964f
Author: Mingyu1991 <115005477+Mingyu1991@users.noreply.github.com>

    fix(autoware_perception_msgs): add Header to tlr messages and change TrafficLightElement.msg status (#68)

commit 76d12470ca1788108a9507cd854e64f5d02e6c7c
Author: Mingyu1991 <115005477+Mingyu1991@users.noreply.github.com>

    feat(autoware_perception_msgs): add UP_LEFT_ARROW and UP_RIGHT_ARROW to traffic_light_element (#67)
=== src/core/external/autoware_auto_msgs (git) ===
commit e1795354161ed54d66659366262578863bd2b862 (HEAD -> tier4/main, origin/tier4/main, origin/HEAD)
Author: Mingyu1991 <115005477+Mingyu1991@users.noreply.github.com>

    add UP_LEFT_ARROW and UP_RIGHT_ARROW for traffic_light (#42)

commit f6642370c6f4f42a5dc0b6c1fc4a21396d4dc34c (humble_with_targets)
Author: Esteve Fernandez <esteve@apache.org>

    fix(autoware_auto_planning_msgs): added action_msgs dependency (#37)

commit 636064fe3e73e33c5df4f65deabe63432ce0a8cd
Author: Takayuki Murooka <takayuki5168@gmail.com>

    chore(autoware_auto_system_msgs): remove FLoat32MultiArrayDiagnostic.idl (#34)
=== src/launcher/autoware_launch (git) ===
commit dfc7eae1b8be6ac97e4343ef2953459e461b5482 (HEAD -> main, origin/main, origin/HEAD)
Author: Takamasa Horibe <horibe.takamasa@gmail.com>

    refactor(lane_change): add namespace for lane-change-cancel (#423)

commit 03c506a683c1f981bd74dfeac97e665af46da880
Author: Satoshi OTA <44889564+satoshi-ota@users.noreply.github.com>

    refactor(avoidance): rename ununderstandable params (#422)

commit f8f72e7c994de950c28335cfb13dd8c65428645c
Author: Fumiya Watanabe <rej55.g@gmail.com>

    fix(autoware_launch): use experimental lane change function (#418)
=== src/middleware/external/heaphook (git) ===
commit ec260d7a7f06f29c04de2c846fa6d2158e770877 (HEAD -> main, tag: 0.1.0, origin/main, origin/HEAD)
Author: Daisuke Nishimatsu <42202095+wep21@users.noreply.github.com>

    chore: prepare release for v0.1.0 (#3)

commit 944d11b66fce5015d76f9aa4f4918c695f010e58
Author: Takahiro Ishikawa <sykwer@gmail.com>

    ci: add build-and-test workflow (#2)

commit 414575ef89f0b834ab1c44d42a208fde5a9ffba1
Author: Daisuke Nishimatsu <42202095+wep21@users.noreply.github.com>

    style: apply lint (#1)
=== src/param/autoware_individual_params (git) ===
commit 09082b6cbb99a840c53878a190616d35a40b569f (HEAD -> main, origin/main, origin/HEAD, humble_with_targets)
Author: Mamoru Sobue <hilo.soblin@gmail.com>

    feat(awsim_sensor_kit): add calibration file of awsim_sensor_kit to use latest universe on AWSIM (#42)

commit 79cff0ba014808050be6f5cb3b4764ba2c96c21c
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

    ci(pre-commit): autoupdate (#35)

commit c1a26518599b54b9f81dae22b738855a36206dc9
Author: awf-autoware-bot[bot] <94889083+awf-autoware-bot[bot]@users.noreply.github.com>

    chore: sync files (#37)
=== src/sensor_component/external/sensor_component_description (git) ===
commit a6a628186b124bc1af73c4f48a6dcd4b441391d3 (HEAD -> main, origin/main, origin/HEAD, humble_with_targets)
Author: taikitanaka3 <65527974+taikitanaka3@users.noreply.github.com>

    feat(pandarXT32): add pandar xt32 xacro (#36)

commit c05075ab1957bf498b68e4a465cf28f266da5d5b
Author: tier4-autoware-public-bot[bot] <98652886+tier4-autoware-public-bot[bot]@users.noreply.github.com>

    chore: sync files (#35)

commit 55a36f3748320b89b7c55a445777551d5cbb7367
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

    ci(pre-commit): autoupdate (#33)
=== src/sensor_component/external/tamagawa_imu_driver (git) ===
commit de4bf6be79aa2968cf2f62e0ebe1ff8a5797e6ad (HEAD -> ros2, origin/ros2, origin/HEAD, humble_with_targets)
Author: Esteve Fernandez <esteve@apache.org>

    build(tamagawa_iwu_driver): added missing dependency (#9)

commit 28ad3cd4fb043e5f92353a540c3531cd4cb7bef3
Author: Daisuke Nishimatsu <42202095+wep21@users.noreply.github.com>

    fix: remove init options (#7)

commit 98309ceef7ff54191401d18d8b9d7e9064093a12
Author: Shinnosuke Hirakawa <8327162+0x126@users.noreply.github.com>

    Feature/configurable frame id (#4)
=== src/sensor_component/external/velodyne_vls (git) ===
commit e8811c856a61d4236d29f6f381bb9be868c4570d (HEAD -> tier4/universe, vrichard/unused_deps, unused_deps)
Author: Vincent Richard <richard-v@macnica.co.jp>

    remove unused depends

commit 55dffdf3b3ef889e149977dc6ab1da124b5176c9 (origin/tier4/universe, origin/HEAD)
Author: Takahiro Ishikawa <sykwer@gmail.com>

    perf(velodyne_convert_node): performance tuning (#39)

commit baeafaf9a376c5798f7b67a77211890c33900f84
Author: Shumpei Wakabayashi <42209144+shmpwk@users.noreply.github.com>

    fix: sign error in return value of getPacket() (#38)
=== src/sensor_kit/external/awsim_sensor_kit_launch (git) ===
commit a1f5993407ffeb4abcf97a49cd1b4034768d97b4 (HEAD -> main, origin/main, origin/HEAD, humble_with_targets)
Author: Mamoru Sobue <hilo.soblin@gmail.com>

    fixed to use xacro.load_yaml (#6)

commit d9022ee9bbfd958c239b673cfbb230eea50607be
Merge: 0d12764 7b7deb4
Author: Shumpei Wakabayashi <42209144+shmpwk@users.noreply.github.com>

    Merge pull request #5 from RobotecAI/feat/shorter_timeout

commit 7b7deb4167d1306294be2896943bbecee964e1d8
Author: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>

    feat: shorten timeout for subscribing dummy lidar
=== src/sensor_kit/sample_sensor_kit_launch (git) ===
commit 5900214b7344a275c8a321bf78f27f8a197e1312 (HEAD -> main, origin/main, origin/HEAD)
Author: Shunsuke Miura <37187849+miursh@users.noreply.github.com>

    feat(sample_sensor_kit_launch): add input topic remapping (#59)

commit b70e5d0b86820ee0ee8880ada9853b7a1b3ea8d3
Author: Yoshi Ri <yoshiyoshidetteiu@gmail.com>

    feat(sample_sensor_kit_launch): add max_sensor range in left/right lidar (#57)

commit 06330e6b07449a3609ced295c0a9ce6a1805ef99 (humble_with_targets)
Author: asana17 <62983821+asana17@users.noreply.github.com>

    feat(sample_sensor_kit_launch): add param file for dummy_diag_publisher (#55)
=== src/universe/autoware.universe (git) ===
commit 6f5af963f4ad01e549941d1547609a86b1ea0b2b (HEAD -> main, origin/main, origin/HEAD)
Author: Zulfaqar Azmi <93502286+zulfaqar-azmi-t4@users.noreply.github.com>

    fix(lane_change): enrich lane change debug markers (#4076)

commit 06cdf326a4aee7d79fb4c79e156a2f4d7f047c53
Author: Takamasa Horibe <horibe.takamasa@gmail.com>

    refactor(lane_change): add namespace for lane-change-cancel (#4090)

commit cdf26944ec86b23b8eba692c922e3778d0168874
Author: Satoshi OTA <44889564+satoshi-ota@users.noreply.github.com>

    fix(behavior_path_planner): fix route update condition (#4091)
=== src/universe/external/eagleye (git) ===
commit 46bc19406613fabdc8de8cb4741b88c018e107df (HEAD -> autoware-main, origin/autoware-main)
Author: Daisuke Nishimatsu <42202095+wep21@users.noreply.github.com>

    build(iron): add missing dependencies in package.xml (#275)

commit e9ca8e37efcac1f1bad287e85d134f4655bab9e2
Author: Esteve Fernandez <github@bot.fernandez.ai>

    build: add missing dependencies (#273)

commit 61c3660fa2e9c4622046b611f29eef4da3a7059d
Author: ryohei sasaki <ryohei.sasaki@tier4.jp>

    Add geographic_msgs dependency (#263)
=== src/universe/external/llh_converter (git) ===
commit 07ad112b4f6b83eccd3a5f777bbe40ff01c67382 (HEAD -> ros2, origin/ros2)
Author: Esteve Fernandez <33620+esteve@users.noreply.github.com>

    build: fix dependencies (#12)

commit b4ad592a7c705ef38b07769512afd8e452b06fb1
Author: ryohei sasaki <ryohei.sasaki@tier4.jp>

    Fix build warnings (#11)

commit 4d4fb18d43800a45e08738dfe18ae3b34903f143
Author: ryohei sasaki <ryohei.sasaki@tier4.jp>

    Remove boost dependency (#9)
=== src/universe/external/morai_msgs (git) ===
commit 04f0a0b6a069fef62e0236189ce23d60abfe97f7 (HEAD -> main, origin/main, origin/HEAD, humble_with_targets)
Author: SoohyeokPark-MORAI <shpark.morai@gmail.com>

    Add Radar messages

commit 6fd6a711e4bbf8a9989b54028e8074acabbbce6f
Merge: 6f89815 89a33ae
Author: shpark - MORAI Inc <92356892+Soohyeok-Park@users.noreply.github.com>

    Merge pull request #5 from Soohyeok-Park/main

commit 89a33aebc741a9b1d9fa87d8c4df90d15fac766b
Author: Soohyeok Park <shpark@morai.ai>

    update msgs
=== src/universe/external/muSSP (git) ===
commit c79e98fd5e658f4f90c06d93472faa977bc873b9 (HEAD -> tier4/main, origin/tier4/main, origin/HEAD)
Merge: f67f4df 4bef541
Author: Takamasa Horibe <horibe.takamasa@gmail.com>

    Merge pull request #2 from tier4/feature/change_compile_option to avoid muSP

commit 4bef541f8331f467d55906ed68a7152b123674cf
Author: tomoya.kimura <tomoya.kimura@tier4.jp>

    feat: change compile option

commit f67f4df5b95fcb28634bb162e09cfeab2ed44d29
Merge: eb7cabf 8edf151
Author: Daisuke Nishimatsu <42202095+wep21@users.noreply.github.com>

    Merge pull request #1 from tier4/fix/suppress_warnings
=== src/universe/external/ndt_omp (git) ===
commit 9a0877ac99cf873d9e984e4f1c485e537503fb7f (HEAD -> tier4/main, origin/tier4/main, origin/HEAD)
Author: Yamato Ando <yamato.ando@gmail.com>

    fix: disable_line_search (#21)

commit eab36ace79c0d5b12b4eba5b900ea6ce665e654f
Author: Esteve Fernandez <esteve@apache.org>

    build(ndt_omp): add ros_environment dependency (#20)

commit d97eb4123b494b841910f6aa84aa1139948a8a74
Author: kminoda <44218668+kminoda@users.noreply.github.com>

    feat(ndt_omp): add multigrid_ndt_omp for dynamic map loading  (#19)
=== src/universe/external/pointcloud_to_laserscan (git) ===
commit 948a4fca35dcb03c6c8fbfa610a686f7c919fe0b (HEAD -> tier4/main, origin/tier4/main, origin/HEAD, humble_with_targets)
Author: Mamoru Sobue <hilo.soblin@gmail.com>

    fix: replace deprecated header for humble (#5)

commit 8057177eeb26a3fd29b6e363e8a9a90d5daf391b
Author: Daisuke Nishimatsu <42202095+wep21@users.noreply.github.com>

    Fix out of range (#4)

commit 43c6abac00d3834e4970aeb63489af4e690193fb
Author: Daisuke Nishimatsu <42202095+wep21@users.noreply.github.com>

    Sync with tier4 master (#1)
=== src/universe/external/rtklib_ros_bridge (git) ===
commit ef094407bba4f475a8032972e0c60cbb939b51b8 (HEAD -> ros2-v0.1.0, origin/ros2-v0.1.0)
Author: Esteve Fernandez <33620+esteve@users.noreply.github.com>

    build: add ament_cmake_auto dependency (#11)

commit 730309aed8f63f6b42fc2cff5dfad6032e605875
Author: Esteve Fernandez <33620+esteve@users.noreply.github.com>

    build: fix dependencies (#10)

commit 73d84d748ec7ba8aebc9f2f0eb39531a8757a5fe
Author: ryohei sasaki <ryohei.sasaki@tier4.jp>

    Fix warning (#9)
=== src/universe/external/tier4_ad_api_adaptor (git) ===
commit a58468edcdaf8698153c85e93fe23807edcb8187 (HEAD -> tier4/universe, origin/tier4/universe, origin/sync-micro-bus, origin/HEAD)
Author: Kosuke Takeuchi <kosuke.tnp@gmail.com>

    refactor(start_planner): rename pull out to start planner (#108)

commit 65fba623366ec3ce214587181a45eec3cbecc55c
Author: Vincent Richard <vincent.francois.richard@gmail.com>

    build: use <buildtool_depend> for autoware_cmake (#103)

commit c3a9235b9af81fb3f6a04ae49a2d317e70a0bff8
Author: tier4-autoware-public-bot[bot] <98652886+tier4-autoware-public-bot[bot]@users.noreply.github.com>

    chore: sync files (#94)
=== src/universe/external/tier4_autoware_msgs (git) ===
commit feb834a37c372d0e83e901ae4f05a7f28a985af2 (HEAD -> tier4/universe, origin/tier4/universe, origin/HEAD)
Author: Kosuke Takeuchi <kosuke.tnp@gmail.com>

    refactor(start_planner): rename pull out to start planner (#91)

commit edbbbbbf3ae0fa6cf071dcaa5ca74ae5179b8e98
Author: Ahmed Ebrahim <36835765+ahmeddesokyebrahim@users.noreply.github.com>

    feat: removing rtc handing (#87)

commit e8df1e66c499b0c10e78ebd314c326cf518a38bc
Author: Satoshi OTA <44889564+satoshi-ota@users.noreply.github.com>

    feat(tier4_planning_msgs): add module name (#89)
=== src/vehicle/external/pacmod_interface (git) ===
commit 689f93cbe9218e127d06d0b937ac62c442b9ce91 (HEAD -> main, origin/main, origin/HEAD)
Author: tier4-autoware-public-bot[bot] <98652886+tier4-autoware-public-bot[bot]@users.noreply.github.com>

    chore: sync files (#59)

commit fa79ce37b0b67005b31f1c0626be353ab524a4d5
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

    chore: pre-commit autoupdate (#56)

commit 1f5acd3cb6dc4d41865bc3add8eff8f0d6fe264b
Author: Tomoya Kimura <tomoya.kimura@tier4.jp>

    fix: fix accel and brake fault messages (#60)
=== src/vehicle/sample_vehicle_launch (git) ===
commit 157238ca77de7b0a59f71a0b28f456741fab3ca2 (HEAD -> main, origin/main, origin/HEAD, humble_with_targets)
Author: Daisuke Nishimatsu <42202095+wep21@users.noreply.github.com>

    fix: suppress xacro warning (#47)

commit 21e38f88bcb9207ab401099617264154a70bb147
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

    ci(pre-commit): autoupdate (#37)

commit c5c591d6ab259db9da2337725fccb313ae0136f1
Author: awf-autoware-bot[bot] <94889083+awf-autoware-bot[bot]@users.noreply.github.com>

    chore: sync files (#46)

```


And yet, I still get the same result:

Terminal 1:
```
$ ros2 launch autoware_launch logging_simulator.launch.xml map_path:=../data/autoware_data_universe/sample-map-rosbag/ vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit | grep -e ndt_scan_matcher -e map_loader -e map_height_fitter -e pose_initializer -e ekf_localizer | tee log.txt
```

- Terminal 2
```
$ ros2 bag play ../data/autoware_data_universe/sample-map-rosbag/sample-rosbag
```

In the logs, ndt_scan_matcher keeps complaining the map service is not available:
```
[INFO] [pose_initializer_node-29]: process started with pid [132406]
[INFO] [automatic_pose_initializer-30]: process started with pid [132409]
[INFO] [ndt_scan_matcher-31]: process started with pid [132433]
[INFO] [ekf_localizer-33]: process started with pid [132458]
[component_container-24] [0m[INFO 1687861368.214610762] [map.map_container]: Load Library: /home/sig/autoware/install/map_loader/lib/liblanelet2_map_loader_node.so (create_component_factory() at ./src/component_manager.cpp:114)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861368.240299001] [localization.pose_estimator.ndt_scan_matcher]: points_queue_size: 1 (NDTScanMatcher() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp:108)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861368.240384159] [localization.pose_estimator.ndt_scan_matcher]: base_frame_id: base_link (NDTScanMatcher() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp:111)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861368.240400452] [localization.pose_estimator.ndt_scan_matcher]: ndt_base_frame_id: ndt_base_link (NDTScanMatcher() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp:114)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861368.240439364] [localization.pose_estimator.ndt_scan_matcher]: trans_epsilon: 0.010000, step_size: 0.100000, resolution: 2.000000, max_iterations: 30 (NDTScanMatcher() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp:127)[0m
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/map/lanelet2_map_loader' in container '/map/map_container'
[aggregator_node-19] [33m[WARN 1687861368.933119133] [Aggregator]: No timestamp set for diagnostic message. Message names: ndt_scan_matcher (checkTimestamp() at ./src/aggregator.cpp:134)[0m
[component_container_mt-1]  (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:298)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861369.394745618] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861370.375947946] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861370.394977843] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861371.376240937] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861371.399815277] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861372.376411255] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861372.400041912] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861373.376609396] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861373.400213846] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861374.376877243] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861374.400552815] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861375.378281922] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861375.400848785] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861376.381314516] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861376.401144268] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861377.381648000] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861377.401445680] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861378.382031534] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861378.401733905] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861379.382368826] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861379.402017073] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861380.382728124] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861380.402258176] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861381.383008251] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861381.402483709] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
[component_container_mt-1] [0m[INFO 1687861382.383251641] [perception.object_recognition.detection.voxel_based_compare_map_filter]: service not available, waiting again ... (VoxelGridDynamicMapLoader() at /home/sig/autoware/src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp:306)[0m
[ndt_scan_matcher-31] [0m[INFO 1687861382.402719313] [localization.pose_estimator.ndt_scan_matcher]: Waiting for pcd loader service. Check if the enable_differential_load in pointcloud_map_loader is set `true`. (MapUpdateModule() at /home/sig/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/map_update_module.cpp:73)[0m
```

I then tried with the dynamic map loading disabled, and it just works as expected.

**Comment by kminoda** [comment]
Thank you. But I still have no clue where the issue comes from, so let me ask some more question:

1. What is the output of `ros2 node info /map/pointcloud_map_loader` in that situation?
2. What does the `/map/pointcloud_map_loader` output in `autoware_launch` terminal? You can see that by e.g. simply launching autoware_launch with `map:=true localization:=false planning:=false perception:=false sensing:=false ...` and see the outputs.

**Comment by kminoda** [comment]
BTW I also updated my Autoware up-to-date and still fails to reproduce the error (so as one of my colleagues)

**Comment by VRichardJP** [comment]
I observe something strange:
- if I start the `logging_simulator.launch.xml`, the lanelet2 and PCD maps do not appear in Rviz
- but if I only start the `map` module, then the maps are visible in Rviz. 

In the first case, the `pointcloud_map_loader` is node is simply never loaded. Even after a few minutes have passed, I get this:
```
$ ros2 node list | grep /map
/map/lanelet2_map_loader
/map/map_container
/map/map_hash_generator
```
No wonder the service is not available.

I don't get this problem at all if only the `map` module is enabled:
```
$ ros2 node list | grep /map
/map/lanelet2_map_loader
/map/lanelet2_map_visualization
/map/map_container
/map/map_hash_generator
/map/pointcloud_map_loader
/map/vector_map_tf_generator
```

The problem is exactly the same with `autoware.launch.xml`: when all modules but `map` are disabled it works, but when everything is running it doesn't. It have tried to see if one particular module is responsible for this, but it does not look like it. At this point, it looks like black magic to me.

**Comment by VRichardJP** [comment]
Using gdb I am trying to understand why the pointcloud map loader component is never started. The program gets stuck forever after loading the `Lanelet2MapLoaderNode` component:
```
Reading symbols from /opt/ros/humble/lib/rclcpp_components/component_container...
(No debugging symbols found in /opt/ros/humble/lib/rclcpp_components/component_container)
Starting program: /opt/ros/humble/lib/rclcpp_components/component_container --ros-args -r __node:=map_container -r __ns:=/map -p use_sim_time:=True -p wheel_radius:=0.383 -p wheel_width:=0.235 -p wheel_base:=2.79 -p wheel_tread:=1.64 -p front_overhang:=1.0 -p rear_overhang:=1.1 -p left_overhang:=0.128 -p right_overhang:=0.128 -p vehicle_height:=2.5 -p max_steer_angle:=0.7
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6deb640 (LWP 55616)]
[New Thread 0x7ffff65ea640 (LWP 55617)]
[New Thread 0x7ffff5de9640 (LWP 55618)]
[New Thread 0x7ffff55e8640 (LWP 55619)]
[New Thread 0x7ffff4de7640 (LWP 55620)]
[New Thread 0x7fffe7fff640 (LWP 55621)]
[New Thread 0x7fffe77fe640 (LWP 55622)]
[New Thread 0x7fffe6ffd640 (LWP 55623)]
[New Thread 0x7fffe67fc640 (LWP 55624)]
[INFO 1687937239.099893814] [map.map_container]: Load Library: /home/sig/autoware/install/map_loader/lib/liblanelet2_map_loader_node.so (create_component_factory() at ./src/component_manager.cpp:114)
[INFO 1687937239.970020821] [map.map_container]: Found class: rclcpp_components::NodeFactoryTemplate<Lanelet2MapLoaderNode> (create_component_factory() at ./src/component_manager.cpp:127)
[INFO 1687937239.970099537] [map.map_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<Lanelet2MapLoaderNode> (create_component_factory() at ./src/component_manager.cpp:129)
[New Thread 0x7fffe5d2b640 (LWP 55643)]
```
If I interrupt the program, I can see ROS2 is stuck waiting for something on cycloneDDS side:
```
^C
Thread 1 "component_conta" received signal SIGINT, Interrupt.
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555555589168) at ./nptl/futex-internal.c:57
57	./nptl/futex-internal.c: No such file or directory.
(gdb) bt
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555555589168) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x555555589168) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555555589168, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff7973ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555555589118, cond=0x555555589140) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555555589140, mutex=0x555555589118) at ./nptl/pthread_cond_wait.c:627
#5  0x00007ffff75461bd in ddsrt_cond_wait () from /opt/ros/humble/lib/x86_64-linux-gnu/libddsc.so.0
#6  0x00007ffff7546285 in ddsrt_cond_waituntil () from /opt/ros/humble/lib/x86_64-linux-gnu/libddsc.so.0
#7  0x00007ffff752f07d in ?? () from /opt/ros/humble/lib/x86_64-linux-gnu/libddsc.so.0
#8  0x00007ffff75da7cf in rmw_wait () from /opt/ros/humble/lib/librmw_cyclonedds_cpp.so
#9  0x00007ffff78a9708 in rcl_wait () from /opt/ros/humble/lib/librcl.so
#10 0x00007ffff7e6edbc in rclcpp::Executor::wait_for_work(std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /opt/ros/humble/lib/librclcpp.so
#11 0x00007ffff7e71ab3 in rclcpp::Executor::get_next_executable(rclcpp::AnyExecutable&, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /opt/ros/humble/lib/librclcpp.so
#12 0x00007ffff7e78f31 in rclcpp::executors::SingleThreadedExecutor::spin() () from /opt/ros/humble/lib/librclcpp.so
#13 0x00005555555565d7 in ?? ()
#14 0x00007ffff7909d90 in __libc_start_call_main (main=main@entry=0x555555556310, argc=argc@entry=28, argv=argv@entry=0x7fffffff3898) at ../sysdeps/nptl/libc_start_call_main.h:58
#15 0x00007ffff7909e40 in __libc_start_main_impl (main=0x555555556310, argc=28, argv=0x7fffffff3898, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffff3888) at ../csu/libc-start.c:392
#16 0x0000555555556775 in ?? ()
(gdb) 
```

Running `pointcloud_map_loader` component in its own container seems to fix the issue, however it does not make any sense:
```python
container = ComposableNodeContainer(
        name="map_container",
        namespace="",
        package="rclcpp_components",
        executable=LaunchConfiguration("container_executable"),
        composable_node_descriptions=[
            lanelet2_map_loader,
            lanelet2_map_visualization,
            # pointcloud_map_loader,
            map_tf_generator,
        ],
        output="screen",
    )
    
    container2 = ComposableNodeContainer(
        name="map_container2",
        namespace="",
        package="rclcpp_components",
        executable=LaunchConfiguration("container_executable"),
        composable_node_descriptions=[
            pointcloud_map_loader,
        ],
        prefix="gnome-terminal --",
        output="screen",
    )

    group = GroupAction(
        [
            PushRosNamespace("map"),
            container, container2,
            map_hash_generator,
        ]
    )
```

```
[INFO 1687938307.248837085] [map.map_container2]: Load Library: /home/sig/autoware/install/map_loader/lib/libpointcloud_map_loader_node.so (create_component_factory() at ./src/component_manager.cpp:114)
[INFO 1687938307.365203669] [map.map_container2]: Found class: rclcpp_components::NodeFactoryTemplate<PointCloudMapLoaderNode> (create_component_factory() at ./src/component_manager.cpp:127)
[INFO 1687938307.365244521] [map.map_container2]: Instantiate class: rclcpp_components::NodeFactoryTemplate<PointCloudMapLoaderNode> (create_component_factory() at ./src/component_manager.cpp:129)
[INFO 1687938307.456190626] [map.pointcloud_map_loader]: Load ../data/autoware_data_universe/sample-map-rosbag//pointcloud_map.pcd (1 out of 1) (loadPCDFiles() at /home/sig/autoware/src/universe/autoware.universe/map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_module.cpp:77)
[INFO 1687938307.473006366] [map.pointcloud_map_loader]: Create PCD metadata, as the pointcloud is a single file. (getPCDMetadata() at /home/sig/autoware/src/universe/autoware.universe/map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp:111)
```

**Comment by kminoda** [comment]
I am sorry I may not be able to be your help, given that the issue cannot be reproduced on my (or my colleagues') environment... Let us know if you have any update on this or got some clue on it.

**Comment by isouf** [comment]
Thank you for raising this issue @VRichardJP.

I think I experience the same problem when I run the [Planning Tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/#parking-scenario):

![Screenshot from 2023-07-07 16-48-08](https://github.com/autowarefoundation/autoware.universe/assets/42570342/b499b0cb-d660-4b66-b5ae-1f09b48069a4)

![Screenshot from 2023-07-07 16-48-24](https://github.com/autowarefoundation/autoware.universe/assets/42570342/a6e4d710-09a8-4c78-9f40-c568005dbee6)

I am running the latest Autoware `main` version with Docker installation (`ghcr.io/autowarefoundation/autoware-universe:latest-cuda`) and NVIDIA GPU enabled.

**Comment by kminoda** [comment]
@isouf I think that issue is irrelevant from the one @VRichardJP has reported. It's due to the [simple_planning_simulator](https://github.com/autowarefoundation/autoware.universe/blob/67c95e9d54783ff295040773feca2b88a6539abc/simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp#L450-L478) where it does not take into account the z position from `/initialpose3d`.

**Comment by isouf** [comment]
> @isouf I think that issue is irrelevant from the one @VRichardJP has reported. It's due to the [simple_planning_simulator](https://github.com/autowarefoundation/autoware.universe/blob/67c95e9d54783ff295040773feca2b88a6539abc/simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp#L450-L478) where it does not take into account the z position from `/initialpose3d`.

Thank you @kminoda for the answer. I was hopping that this issue is related to the fact that I am not able to set the `OperationMode` to `AUTO` despite having the `Routing=SET` and the `Localization=INITIALIZED`. As you can see in the images attached above, the `AUTO` button is (for some unknown reason) disabled.

**Comment by kminoda** [comment]
@isouf Thank you for the clarification! And not sure if it's related to the z-axis issue. Maybe better to create another issue or discussion.

**Comment by qianxingqx** [comment]
> 

Hello, I have also encountered this problem. How did you solve it? Thanks!

**Comment by qianxingqx** [comment]
> > @isouf I think that issue is irrelevant from the one @VRichardJP has reported. It's due to the [simple_planning_simulator](https://github.com/autowarefoundation/autoware.universe/blob/67c95e9d54783ff295040773feca2b88a6539abc/simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp#L450-L478) where it does not take into account the z position from `/initialpose3d`.
> 
> Thank you @kminoda for the answer. I was hopping that this issue is related to the fact that I am not able to set the `OperationMode` to `AUTO` despite having the `Routing=SET` and the `Localization=INITIALIZED`. As you can see in the images attached above, the `AUTO` button is (for some unknown reason) disabled.

Hello, I have also encountered this problem. How did you solve it? Thank you!

**Comment by qianxingqx** [comment]
> @isouf Thank you for the clarification! And not sure if it's related to the z-axis issue. Maybe better to create another issue or discussion.

Thank you for your answer. I have the same problem with @isouf . Do you have any suggestions for this issue?

**Comment by kminoda** [comment]
@qianxingqx You mean about the planning simulator with the map from tutorial, right?
It works fine with the latest Autoware on my PC. If the issue persists, please provide us with your specific environment and way to reproduce. 
![image](https://github.com/autowarefoundation/autoware.universe/assets/44218668/6baab113-4576-4d0b-867e-6d5c5e8778b6)

Also, since this thread is getting longer, it would be better to create another issue.

**Comment by kminoda** [comment]
@VRichardJP Since this is staled, I would like to close this issue in a week if you don't encounter this issue any longer or not up-to-date. Please feel free to reopen this issue if you have any further issues. Thank you for your understanding.

**Comment by VRichardJP** [comment]
No problem.

As I read back some of my comments, it could be related to https://github.com/ros2/rclcpp/issues/2362
